---
- hosts: localhost
  connection: "local"
  gather_facts: false
  vars_files:
    - group_vars/aws 

  tasks:
  - name: "Terminate tagged EC2 instances"
    ec2_instance:
      state: "absent"
      region: "{{ ec2_region }}"
      filters:
        "tag:Name": rheldemo 

  - name: "Remove security group"
    ec2_group:
      name: "{{ ec2_security_group }}"
      region: "{{ ec2_region }}"
      state: "absent"
